name: run-metadata-update
run-name: Runs metadata_update.py
on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 1
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: null
        python-version: 3.1
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Run Python Script
        run: python metadata_update.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with: null
        author_name: jbwexler
        author_email: jbwexler@tutanota.com
        message: Automatic update via github workflow
        push: true
